// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK6UqIRvpGqr3fLM308YZ-lmshFyAfbfA',
    appId: '1:831468773599:android:9a68dadd0303b3c38bc96a',
    messagingSenderId: '831468773599',
    projectId: 'hepato-diagnosis-d783c',
    storageBucket: 'hepato-diagnosis-d783c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--yIac9XCYfrvAwyr07D__tSrBnfTFNc',
    appId: '1:831468773599:ios:399eecf5850424ae8bc96a',
    messagingSenderId: '831468773599',
    projectId: 'hepato-diagnosis-d783c',
    storageBucket: 'hepato-diagnosis-d783c.firebasestorage.app',
    androidClientId: '831468773599-74k18tr0ou12ricrleshtd3jr53p5cgv.apps.googleusercontent.com',
    iosClientId: '831468773599-q5uog2uqlptol3p3bo4ansojhl029tbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}